Repository AY2324S1-CS2113-T18-3/tp, pull requests merged in 2023-10, with the labels that each got.

#26 Bryan UI class added
  src/main/java/seedu/duke/Ui/Ui.java
Labels: type.Task, priority.Medium

#30 Bryan Parser Class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser/Parser.java
Labels: type.Task, priority.High

#32 Bryan income class
  src/main/java/seedu/duke/Commands/KaChinnnngException.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FinancialRecord/FinancialRecord.java
  src/main/java/seedu/duke/FinancialRecord/Income.java
  src/main/java/seedu/duke/Parser/Parser.java
  src/main/java/seedu/duke/Ui/Ui.java
Labels: type.Task, priority.High

#33 added commands class
  src/main/java/seedu/duke/Commands/Commands.java
  src/main/java/seedu/duke/financialrecords/FinancialRecord.java
  src/main/java/seedu/duke/financialrecords/Income.java
Labels: type.Task, priority.High

#35 added the add income functionality
  src/main/java/seedu/duke/Commands/IncomeManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser/IncomeParser.java
  src/main/java/seedu/duke/Parser/Parser.java
  src/main/java/seedu/duke/Ui/Ui.java
  text-ui-test/input.txt
Labels: type.Epic, priority.High

#38 added the list income function
  src/main/java/seedu/duke/Commands/IncomeLister.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser/Parser.java
  src/main/java/seedu/duke/Ui/Ui.java
Labels: type.Story, type.Task, priority.High

#45 minor bug fixing and added javadoc
  src/main/java/seedu/duke/Commands/Commands.java
  src/main/java/seedu/duke/Commands/IncomeLister.java
  src/main/java/seedu/duke/Commands/IncomeManager.java
  src/main/java/seedu/duke/Commands/KaChinnnngException.java
  src/main/java/seedu/duke/Commands/UsageInstructions.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser/IncomeParser.java
  src/main/java/seedu/duke/Parser/Parser.java
  src/main/java/seedu/duke/Ui/Ui.java
  src/main/java/seedu/duke/financialrecords/FinancialRecord.java
  src/main/java/seedu/duke/financialrecords/Income.java
Labels: type.Bug, priority.Low

#60 edited testsh and expected output
  src/main/java/seedu/duke/commands/UsageInstructions.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.Low

#87 Bryan find function
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/financialrecords/Expense.java
  src/main/java/seedu/duke/financialrecords/Food.java
  src/main/java/seedu/duke/parser/FindParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Story, type.Enhancement, type.Task, priority.High

#88 made it such that the log file will be in a folder instead
  src/main/java/seedu/duke/commands/IncomeManager.java
  src/main/java/seedu/duke/financialrecords/Income.java
  src/main/java/seedu/duke/parser/IncomeParser.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Bug, severity.Low

#91 added logging and assertions to findCommand class
  src/main/java/seedu/duke/commands/FindCommand.java
Labels: type.Task, priority.Medium

#101 updated UserGuide for FindCommand class and edited code snippets
  docs/DeveloperGuide.md
  images/FindCommand_SequenceDiagram.png
  logs/Income.log
  logs/IncomeManager.log
  logs/IncomeParser.log
  logs/Parser.log
  src/main/java/seedu/duke/parser/FindParser.java
Labels: type.Epic, type.Task, priority.Medium

#102 Add Edit Feature
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Commands.java
  src/main/java/seedu/duke/commands/DeleteExpenseCommand.java
  src/main/java/seedu/duke/commands/DeleteIncomeCommand.java
  src/main/java/seedu/duke/commands/EditExpenseCommand.java
  src/main/java/seedu/duke/commands/EditIncomeCommand.java
  src/main/java/seedu/duke/commands/IncomeManager.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/EditExpenseCommandTest.java
  src/test/java/seedu/duke/commands/EditIncomeCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#110 included incomeManager JUnit test and incomeLister JUnit test. edited…
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/IncomeLister.java
  src/main/java/seedu/duke/parser/IncomeParser.java
  src/test/java/seedu/duke/commands/IncomeListerTest.java
  src/test/java/seedu/duke/commands/IncomeManagerTest.java
  src/test/java/seedu/duke/parser/IncomeParserTest.java
Labels: type.Task, priority.Medium
